### ISSUE TITLE
Support Rotations: New Hire Training on January 2

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/BuddyCore#1]
We might have a new hire who will start on January 2 (Saturday, weekend day) so we will need to prepare the training outside of normal schedule.

The date is still to be confirmed.

**Comment by serabi** [comment]
New hire is confirmed to be starting on 2nd (which is a Wednesday) meaning that their training will be running Wednesday and Thursday, with a 1:1 session with their support rotation buddy on Thursday. They'll then do 5 days of tickets and start chat on Wednesday, January 9th. 

So far, I have a buddy lined up for the new hire and have lined up coverage for all three training sessions. 

Next steps will be to publish a post with this information on the supportrotationsp2.

**Comment by katinthehatsite** [comment]
Okay great, thanks for the update. Once the post goes up, I will email the new hire with the details of the rotation and set up their permissions. Could you please cc Matt Wondra in the comments of the post to grant SA? Since the training is lat minute, we would need to make sure SA access won't be missed!

**Comment by serabi** [comment]
Done! :)

https://supportrotationsp2.wordpress.com/2018/12/21/trainings-for-the-week-of-december-31st/

**Comment by katinthehatsite** [comment]
All permissions for Donut, ZD etc. have been granted on my end.
