### ISSUE TITLE
Work on Trial Buddy Wrangling FG page

### ISSUE THREAD

**Issue by thebud15** [Automattic/BuddyCore#13]
Let's work on creating a field guide page that outlines the process of _how_ to wrangle trial buddies. 
We can collaborate on that here: https://docs.google.com/document/d/1vBwJxq47t2N1FfxlJYrF-boXOmHht42IgGUWIYa36Z4/edit

**Comment by thebud15** [comment]
@mbhthompson Looks like I'm ready to publish. Would you be able to let me know how it looks and when you give the green light, we'll go live: https://fieldguide.automattic.com/?page_id=71300&preview=true

**Comment by mbhthompson** [comment]
@thebud15 looks great! I made a few small edits (mainly spelling or fixing the link to the checklist post) and published :)
