### ISSUE TITLE
Draft and post expectations for guild members

### ISSUE THREAD

**Issue by thebud15** [Automattic/BuddyCore#15]
>Draft and post expectations for guild members.

I'll be working on this writeup, per https://fieldguide.automattic.com/build-a-guild-handbook/#checklist

**Comment by thebud15** [comment]
Finished rough draft and open to feedback from the team :)

**Comment by serabi** [comment]
Had one comment, left it on the Google doc. Thank you for writing all of this up, @thebud15 :)

**Comment by thebud15** [comment]
Suggestion taken. Thanks @serabi!
