### ISSUE TITLE
Buddy Feedback Form

### ISSUE THREAD

**Issue by mbhthompson** [Automattic/BuddyCore#16]
Let's create a buddy feedback form that trials, HEs, and support rotations can use to provide random feedback at any time. This form can exist on our [BCORE P2](https://buddyp2.wordpress.com/) in the form of a link or button.

The JPOP leads recently did something similar. They created a Google Form for the team to submit feedback/questions at any time. The form is linked to in the menu on [+jpophappy](https://jpophappy.wordpress.com/)

**Comment by thebud15** [comment]
This is a little different, but related. Let's see what we can do to revise the current one here: https://docs.google.com/forms/d/e/1FAIpQLSc0lzL2CedDhMxjVtM7u3x7pxedAj9Mp_A2wMP0ZdbWo_KiZA/viewform

I used this for the summer buddy crew. Let's see what we can do to use this for this last Fall (Let's start referring to these as quarters) aka Q3/4 2018 round. Do we want to change any of the questions? Move it into CrowdSignal? @mbhthompson

**Comment by thebud15** [comment]
Just noting that the above has been done and sent our to our Q4 2018 buddies here: 
https://a8c.slack.com/archives/GCJ1RJ2CF/p1545003960024400

**Comment by mbhthompson** [comment]
@thebud15 I've got a simple form created here: 

https://docs.google.com/forms/d/e/1FAIpQLSdY6G1fJsnSJBItRm_2kgkEfPP2Umgul5T54zGDPunP6kvBuA/viewform?usp=sf_link

I'm looking for this to be very open-ended (so no specific questions) and something people can use to share any random feedback that comes to mind at any point in time (outside of any surveys we may send after buddying trials, onboarding etc).

If you're cool with it, I can add it to the menu on our p2.

**Comment by thebud15** [comment]
@mbhthompson I like the open ended idea. Let's go for it!

**Comment by mbhthompson** [comment]
Done!
