### ISSUE TITLE
Documenting Finding Buddies For New Hires In Mobile

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/BuddyCore#22]
As discussed with Sarah, I am going to write a page on wrangling special cases and she will go over it and check if something is not clear.

**Comment by katinthehatsite** [comment]
Started working on the page here: https://automattictraining.wordpress.com/?page_id=70115&preview=true but only the mobile part is ready so far

**Comment by katinthehatsite** [comment]
The page is ready for review

**Comment by serabi** [comment]
Reviewed - looks good. Published here: https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/wrangling-special-cases-new-hires-mobile-and-woo/
