### ISSUE TITLE
Trial Buddy Wrangling Checklist Template

### ISSUE THREAD

**Issue by mbhthompson** [Automattic/BuddyCore#24]
Let's create a checklist template that we can use to keep track of wrangling duties per trial batch. This checklist can be posted for transparency on our BCORE P2.

**Comment by mbhthompson** [comment]
@thebud15 I've got a draft saved that you can review here: 

https://buddyp2.wordpress.com/?p=72&preview=true

The only thing I need to add is the link to the FG page once it is created. 

Lmk your thoughts :)

**Comment by thebud15** [comment]
@mbhthompson I like it! I'm hoping to get the FG page published by tonight or tomorrow. Maybe we can link the "During week 4..." portions to a OneBin of the message we send out just to make it a bit easier to find.

**Comment by thebud15** [comment]
Created a OneBin here: https://mc.a8c.com/pb/1ff7d/#plain

**Comment by mbhthompson** [comment]
@thebud15 good idea! I've updated the draft to include links to an example buddies on call post, the OneBin you created, and an example end of quarter survey. 

Once you have the FG page created, I'll add the link to that, and we can start using the template :)

**Comment by thebud15** [comment]
I added the link for the FG page into this checklist, pending publishing it.

**Comment by mbhthompson** [comment]
@thebud15 Awesome! Everything looks good and I've published the post. I also checked off the items that have already been done for this quarter so far.
