### ISSUE TITLE
WHTA post

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/BuddyCore#27]
- draft by Friday night, January 11 on #buddying-happiness channel
- includes the following:
    a. D'Oh Buddying Overview
    b. Process
    c. Helpful links (FG and BCORE p2)
    d. Feedback about D'Oh Buddying from other HEs
    e. Next Steps: P2 post to be published for Team Leads

**Comment by rosepajaroja** [comment]
### D’Oh Buddying 2019

In the past month, since the [update from Buddy Core](https://wehavetheanswers.wordpress.com/2018/12/13/buddy-core-update-december-2018/) was published we have been working on redesigning the process of D’Oh Buddying. 

### Overview
A D’OH Buddy is going to be like a mentor or a buddy of a new hire, who will be in charged with introducing the a8c culture. 

### Goals

- Share common values, goals, and background of our team
- Guide to tools, squads, and projects
- Choosing optimal work environment

### D’OH Buddying Process Guide

![Alt text](https://monosnap.com/image/bisiU5FgeLfM95M2HB1AMWIoU3GuVM.png)

You can also refer to our updated FG docs for details. 
https://fieldguide.automattic.com/developing-our-happiness-doh-guide/

### Helpful Links

[FG document
](https://fieldguide.automattic.com/developing-our-happiness-doh-guide/)
[Buddy Core P2
](https://buddyp2.wordpress.com/)
[D'OH Program – HE Availability Spreadsheet](https://docs.google.com/spreadsheets/d/1uhqVyVq1m0lNTKaNN96_ZA8MAI1clNjuIj4pBGvWgVw/edit#gid=0)

### Help from Leads:

We updated D'OH Program – HE Availability Spreadsheet. We are to publish another post to invite all team leads to update their HE’s availability for Buddying. We’re hoping to get this completed by end of week, **January 20, 2019**. We really appreciate all your help. 😊

**Comment by rosepajaroja** [comment]
WHTA January 17
TL P2 January 24

**Comment by thebud15** [comment]
Here's an idea of some text that can be combined with yours for a P2 post to get that "motivating" component you asked for help with :) 

> Hey team! We at Buddy Core have been working hard to really revamp our D'Oh Buddy process. It's a helpful method for helping new HEs develop their Happiness as they join us here at a8c. There is room for even more growth, and that's where you can get involved. 
> 
> We will soon be looking to have leads audit their teams' statuses when it comes to D'Oh Buddying, and we would like to have as much participation in the program from available buddies as possible. 
> 
> We are working on revamping the conversation topics, streamlining the buddy selection process for leads and taking past feedback on the process to make it better than it's ever been. We'd love to have YOU as part of it. Interested in being available to help out with the process? Take a look over this field guide page for more info on what's involved and discuss it with your lead. You may not be asked for assistance in the very near future, but the more availability we have, the better!
> 
> Questions? Comments? Find out more info on +buddyp2 and reach out to us there!

**Comment by fhaps** [comment]
I just finished my draft of the post, and only now I saw your comment above, @thebud15! 😅

Here's my draft: https://wordpress.com/post/buddyp2.wordpress.com/127

I'll post this on WHTA once we agree on a final version, but I saved the draft in Buddy P2 for now. 

Please feel free to make any changes you see fit. We can definitely integrate any of the text Eric suggested above.

Let me know what you two think! @rosepajaroja

**Comment by thebud15** [comment]
@fhaps I think what you wrote looks great!

**Comment by thebud15** [comment]
One thing, I don't know that we need to have people comment if they're interested... maybe just if they have questions. The leads are going to update that for us, so I don't think we really need to worry about collecting names of who's interested on there too much.

**Comment by fhaps** [comment]
@thebud15  I agree, but the main reason I included that was just to give people a clear next step. Just to avoid a situation where someone is interested but doesn't really know what to do next (since leads won't reach out to their teams about it for a couple of weeks).

**Comment by thebud15** [comment]
@fhaps Ah gotcha. I just wouldn't want HE's to think that they're _only_ qualified/volunteering as D'Oh buddies if they comment on that post, you know? Do you think that might be a potential issue?

**Comment by fhaps** [comment]
@thebud15 Hadn't thought about that, but I guess once leads reach out to their teams, they can "sign up" with them regardless of whether they commented or not. 

Would it be better if we change the "comment on this post" to "let us know"?

What do you think, @rosepajaroja?

**Comment by thebud15** [comment]
@fhaps Maybe something like "If this sounds interesting to you and something you'd like to get involved with, please talk to your lead about it! Soon, we'll be enlisting their help in collecting the names of those who are able to join."

**Comment by thebud15** [comment]
Posted, nice job!
