### ISSUE TITLE
Support Rotations: Proofread FG before move to two weeks rotations

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/BuddyCore#3]
We would need to proofread some FG pages before we move to 2-week rotations:
https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/buddying-a-new-hire/
https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/
https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/buddying-a-new-hire-a-detailed-guide/
https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/support-rotation-for-a-new-hire/

**Comment by serabi** [comment]
https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/buddying-a-new-hire/

This is updated. Will need further updates once we move from Humanity (as it has a section referencing Humanity). I'll loop back around to that section later.

**Comment by serabi** [comment]
https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/
https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/buddying-a-new-hire-a-detailed-guide/
https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/support-rotation-for-a-new-hire/

Updated.

**Comment by serabi** [comment]
Marking this as done. Will update the Humanity references in the beginning of December - have added that to my personal to-do list.

**Comment by katinthehatsite** [comment]
Updated Humanity references and UTC times inconsistency on this one: https://fieldguide.automattic.com/buddy-guide-on-wordpress-com/buddying-a-new-hire/
