### ISSUE TITLE
Support Rotations: Proofread Support Rotations P2

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/BuddyCore#4]
We would need to proofread support rotations P2: https://supportrotationsp2.wordpress.com/faq-sa-zendesk-access-and-more/ to make sure everything is updated for two weeks rotations

**Comment by serabi** [comment]
Somehow I broke the checkboxes on this page:
https://supportrotationsp2.wordpress.com/checklist-for-buddying-a-new-hire/

Figuring out how to fix this now. Otherwise, this P2 is updated.

**Comment by serabi** [comment]
Done
