### ISSUE TITLE
Support Rotations: Update/Rewrite The Support Buddies Page

### ISSUE THREAD

**Issue by katinthehatsite** [Automattic/BuddyCore#8]
https://wehavetheanswers.wordpress.com/training/buddies/
I see that it is still on We Have the Answers, we have some info that needs to be updated

**Comment by serabi** [comment]
Updated page!

**Comment by katinthehatsite** [comment]
The page was also linking to the +trainingp2 so made an update there and added the link to buddy guide for new hires. Closing again :)
